import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    document.addEventListener('csEvent', function (event) {
      var data = event.detail;
      window.goAdFree = true;
  });
  })
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="pomegrant" content="sldcodes.testnet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
}
